### ISSUE TITLE
av2geobau conversion error

### ISSUE THREAD

**Issue by edigonzales** [edigonzales/avdpool-camel#8]
```
Route Id: _av2geobau_ 
 Date: 2019-10-14 10:54:16 
 File: /avdpool_data/av2ch/251300.itf 
 Message: could not convert: /avdpool_data/av2ch/251300.itf 
 Stacktrace: java.lang.Exception: could not convert: /avdpool_data/av2ch/251300.itf
	at ch.so.agi.camel.processors.Av2GeobauProcessor.process(Av2GeobauProcessor.java:29)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:454)
	at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:223)
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:187)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Es ist ein Fehler in der `av2geobau`-Bibliothek. Sollte mit Pull-Request gefixed sein: https://github.com/claeis/av2geobau/pull/2

**Comment by edigonzales** [comment]
fixed https://github.com/claeis/av2geobau/commit/e8c15d8727b006486b4f2e353a512c6dc548f20f

Betroffene ITF werden in der Test-Umgebung konvertiert.
